portainer:
  restart: 'always'
  image: portainer/portainer
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  ports:
    - "9000:9000"

logspout:
  restart: 'always'
  image: gliderlabs/logspout
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  command: syslog://logs5.papertrailapp.com:28037
  environment:
  - SYSLOG_HOSTNAME=${SYSLOG_HOSTNAME}
